### ISSUE TITLE
Add Type/Class information for variables

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/validate#27]
It may be useful/necessary to specify the data types of the variables.

Currently this can be done by adding a rule for each column, but it could be made more strict. 
Especially when a duplicate variable name of different type is used in a large rule set.

**Comment by markvanderloo** [comment]
Since R doesn't allow duplicate names in data.frames, it can only be an issue when comparing to a reference dataset. Implementing symbol matching on type & name is possible but I think it severely complicates the semantics of a rule set. Not convinced whether users are helped by that. I may be missing something (got an example?).
