### ISSUE TITLE
naming of "short" and "long" properties in rule

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/validate#34]
I suggest "title" and "description" (or "desc") in stead of "short" and "long". 

Short and long may confuse the user to believe these are integers.

**Comment by edwindj** [comment]
Other alternative for short/title would be "label" which is more R-like

**Comment by markvanderloo** [comment]
How about 'title' and 'info'? it is shorter than 'description' and sort of matches the convention in `expect_that`-like functions. OTAH 'info' is less descriptive (everything is info)

**Comment by edwindj** [comment]
I like the shortness of "info", but "description" seems more standard and specific.

**Comment by markvanderloo** [comment]
Ok, let's do 'name', 'title', 'description'. I guess we need /[gs]etter/ functions of the same name.

**Comment by markvanderloo** [comment]
done

**Comment by markvanderloo** [comment]
Turns out `title` is an existing function in one of the recommended packages (`graphics`).

This means we are allowed to make our own `title` but `graphics::title` is masked.

I can live with that but I'd like to hear what you think. [graphwords.com](http://graphwords.com/word#title) didn't give me good inspiration for a better word...

**Comment by edwindj** [comment]
Is 'label' also taken? (http://www.thesaurus.com/browse/title)
