### ISSUE TITLE
Implement scope for a rule?

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/validate#41]
Currently a rule has an implicite scope:
it can act with scope:
- "record" of a dataset (e.g. `height > 50`)
- "dataset" (`mean(height) > 50`)
- "crossdataset" (`mean(height) < 1.2 * mean(ref$height)`)

It would be useful for reporting and dependent packages to retrieve explicitly the scope of rules, or to 
retrieve rules of a specific scope type.

P.S.

It would also be nice to have:
- "group", e.g. `group_by(gender) %>% mean(height) > 50`

**Comment by markvanderloo** [comment]
Agreed. Since `confront` is pipe-ready, we could also make it aware of `dplyr`'s grouping, e.g.

```
iris %>% group_by(Species) %>% check_that(Sepal.Length < 1.5 * median(Sepal.Lenght)
%>% summary()
```

I'd put this on the 0.2 list though. 

Actually, our `indicator` is fairly close to what `summarize` does in `dplyr`. We need to think about that as well.

**Comment by edwindj** [comment]
I had exactly the same thought on dplyr and grouping...

**Comment by markvanderloo** [comment]
I think that the following sequence should be more or less intuitive, but we need to have 'keys' better implemented.
```
v <- validator(Sepal.Length > 0, Sepal.Width < Sepal.Length)
iris %>% confront(v) %>% as.data.frame() %>%  group_by(Species)
```
Currently, there's not `as.data.frame` yet for `validation` objects because translation is not always obvious, given the various output dimension structures (that are available at runtime only). 

This would also be something for 0.2 I guess. It requires some carefull thought.

**Comment by markvanderloo** [comment]
This is done in [GenericValidationRules](https://github.com/SNStatComp/GenericValidationRules), which implements functions that make these operations easier (or will eventually).
