### ISSUE TITLE
validate is unstable on large data

### ISSUE THREAD

**Issue by Plebejer** [data-cleaning/validate#86]
I work with `validate` on a dataset with ~750,000 rows and ~ 3,000 columns, which is ~ 17GB in memory (according to RStudio). Very often when I want to access results - like `values(cf)` or `aggregate(cf)` - from the confrontation object, R crashes without any error message. 

Sometimes I get the following error message:

> Error in unlist(x, recursive = FALSE) : 
>   long vectors not supported yet: memory.c:1668

This sounds as if it is related to the available memory. However, there are more than 50 GB of free memory (from 128 GB total) when R crashes (according to the task manager).

**Comment by markvanderloo** [comment]
The amount of data gathered by `confront` depends on the type and nr of rules. For example, if you have 3000 range checks, (two rules per variable), you would get a list (inside the confrontation object) of 6000 elements, each a `logical` vector each of length 750k. When you call `values`, this is folded into an array containing a copy of those logicals. We need to walk this route because depending on the rule, you may get results of different dimension structure.

In any case, you quickly get more validation data than actual data, but this is to be expected. The number of rules we encounter is typically about 1.5-3 times the number of variables. You can also compare it with a data base: the logging information stored for rollback is larger than the data you're storing.

Now for the error message: `memory.c` is a base `R` file, so I think that there is an operation in there where base R does not yet support long vectors. The `validate` package is written almost completely in pure R. We only use compiled code for rules of the functional dependency type.

A workaround is to chunk your data set, compute results and then combine them.
